# The run name: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml
name: Auth-$(Build.SourceBranchName)-$(Date:dd.MM.yyyy)-$(Rev:r)

resources:
  pipelines:
  - pipeline: Dev-Trigger
    source: Dev-Trigger
    trigger:
      branches:
        include:
        - refs/heads/dev
        
trigger:
  branches:
    include:
    - refs/heads/dev
  paths:
    include:
    - EveryEng/Auth
    - .azuredevops/pipelines/auth.yaml
    exclude:
    - k8s

pool:
  vmImage: ubuntu-latest
  # we are by default using a microsoft hosted agent with a parameterized default image  
  #name: EeAgentPool 

variables:
 - template: templates/vars/global.yaml 
 - template: templates/vars/dev.yaml
 - template: templates/vars/prod.yaml
 
 

stages:
####### Build And Package the Apps into containers #####
- template: templates/stages/build-dev-prod.yaml
  parameters:
     ProjectPath: EveryEng/Auth/EveryEng.Api.Authentication        
     AppName: authentication
     SectionName: auth
     IsService: true
     MaxAksAppCount: 3
