apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.96.0
    helm.sh/chart: opentelemetry-collector-0.83.1
  name: opentelemetry-collector

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: opentelemetry-collector
      app.kubernetes.io/name: opentelemetry-collector

  template:
    spec:
      serviceAccount: sa-azdevops
      serviceAccountName: sa-azdevops
      terminationGracePeriodSeconds: 30


