apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: #{aksappname}#
  labels:    
    app.kubernetes.io/name: #{aksappname}#  
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: #{aksappname}#