variables:
 - name: prodaksADOEnvName
   value: ee-prod-aks.agritech
 - name: prodaksAppNamespace
   value: agritech
 - name: prodappConfigKey
   value: agritech-env
 - name: prodappEnvName
   value: prod