variables:
 - name: devaksADOEnvName
   value: ee-staging-aks.everyeng
 - name: devaksAppNamespace
   value: everyeng
 - name: devappConfigKey
   value: everyeng-env
 - name: devappEnvName
   value: dev