variables:
 - name: devaksADOEnvName
   value: ee-staging-aks.agritech
 - name: devaksAppNamespace
   value: agritech
 - name: devappConfigKey
   value: agritech-env
 - name: devappEnvName
   value: dev