global using AgriTech;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using FluentValidation;
global using FluentValidation.Results;
global using System.Runtime.CompilerServices;
global using AgriTech.Dto;
global using System.Reflection;
global using AgriTech.Infrastructure.Behavior;